data_summary:
  data_first_cols: [
    episode_id, 
    epsilon, 
    learning_rate, 
    gain_delta, 
    total_agent_decisions, 
    final_t_sec,  
    total_reward, 
    performance,
    end_termination_reason,
    final_kp_pendulum_angle, 
    final_ki_pendulum_angle, 
    final_kd_pendulum_angle,
    final_kp_cart_position,
    final_ki_cart_position,
    final_kd_cart_position
  ]
  data_stats: [
    pendulum_angle_raw,
    pendulum_angle_norm,
    pendulum_velocity_raw,
    pendulum_velocity_norm,
    cart_position_raw,
    cart_position_norm,
    cart_velocity_raw,
    cart_velocity_norm,
    error_pendulum_angle,
    derivative_error_pendulum_angle,
    integral_error_pendulum_angle,
    control_action_pendulum_angle,
    u_eff_pendulum_angle,
    delta_u_eff_pendulum_angle,
    error_cart_position,
    derivative_error_cart_position,
    integral_error_cart_position,
    control_action_cart_position,
    u_eff_cart_position,
    delta_u_eff_cart_position,
    cart_force,
    error_pendulum_angle_mean_squared,
    error_cart_position_mean_squared,
    derivative_error_pendulum_angle_mean_squared,
    derivative_error_cart_position_mean_squared,
    delta_u_eff_pendulum_angle_mean_squared,
    delta_u_eff_cart_position_mean_squared,
    integral_error_pendulum_angle_mean_squared,
    integral_error_cart_position_mean_squared,
    L_e_pendulum_angle,
    L_e_cart_position,
    L_edot_pendulum_angle,
    L_edot_cart_position,
    L_delta_u_pendulum_angle,
    L_delta_u_cart_position,
    principal_gate_L_edot_pendulum_angle,
    principal_gate_L_edot_cart_position,
    principal_gate_L_delta_u_pendulum_angle,
    principal_gate_L_delta_u_cart_position,
    principal_contribution_L_edot_pendulum_angle,
    principal_contribution_L_edot_cart_position,
    principal_contribution_L_delta_u_pendulum_angle,
    principal_contribution_L_delta_u_cart_position,
    reward_kp_pendulum_angle,
    reward_ki_pendulum_angle,
    reward_kd_pendulum_angle,
    reward_kp_cart_position,
    reward_ki_cart_position,
    reward_kd_cart_position,
    extra_penalty_instantaneous_pendulum_angle,
    extra_penalty_instantaneous_cart_position,
    extra_penalty_pendulum_angle,
    extra_penalty_cart_position,
    extra_bonus_goal_pendulum_angle,
    extra_bonus_goal_cart_position,
    extra_bonus_band_pendulum_angle,
    extra_bonus_band_cart_position,
    extra_conditional_dynamic_penalty_pendulum_angle,
    extra_conditional_dynamic_penalty_cart_position,
    extra_conditional_dynamic_incentive_pendulum_angle,
    extra_conditional_dynamic_incentive_cart_position,
    extra_conditional_dynamic_incentive_tracking_pendulum_angle,
    extra_conditional_dynamic_incentive_tracking_cart_position,
    extra_conditional_dynamic_incentive_capture_pendulum_angle,
    extra_conditional_dynamic_incentive_capture_cart_position,
    extra_conditional_dynamic_incentive_direction_pendulum_angle,
    extra_conditional_dynamic_incentive_direction_cart_position,
    extra_conditional_dynamic_incentive_effort_pendulum_angle,
    extra_conditional_dynamic_incentive_effort_cart_position,
    extra_total_pendulum_angle,
    extra_total_cart_position
  ]
